ops/deploy_s3.sh

Updated version of the script initially proposed in #1. This version of the script builds _and_ deploys the site.
Usage: `./ops/deploy.sh <local-build-dir> <s3-bucket>`
The `<local-build-dir>` and `<s3-bucket>` args are optional.

Script to build and deploy to s3

---

Gemfile
Gemfile.lock
_codebooks/codebook-ffs-claims-trimmed.xml
_config.yml
_layouts/codeset.html
_plugins/api_codings.rb

The magic happens in the api_codings.rb plugin file being added. It
takes in the codebook XML files produced by
<https://github.com/CMSgov/bluebutton-data-model/tree/master/bluebutton-data-model-codebook-extractor>
and uses them to produce Jekyll output pages.
Definitely not 100% done, but a solid first pass. Known issues:
* The real codebook XML files are missing, as the code used to produce
them has some not-yet-fixed bugs. Added a bespoke, artisal, locally
produced (and Hipster-friendly) sample in the meantime.
Even this sample still has some problems, such as the not-quite-empty
value entries.
* The layout/design of the rendered pages is bad. Very.
https://issues.hhsdevcloud.us/browse/CBBI-314

CBBI-314: First cut of Jekyll generator for API codesets

---

ops/terraform/bluebutton.cms.gov/main.tf
ops/terraform/bluebutton.cms.gov/templates/nginx.conf
ops/terraform/bluebutton.cms.gov/variables.tf

- Redirect http to https requests
- Enforce https by setting `Strict-Transport-Security` header
- Configure the ALB with TLS certificate
- Update to ALB health check endpoint

Updates to make sure the site is served over https only

---

ops/terraform/bluebutton.cms.gov/main.tf
ops/terraform/bluebutton.cms.gov/templates/bucket-policy.json
ops/terraform/bluebutton.cms.gov/templates/nginx.conf
ops/terraform/bluebutton.cms.gov/templates/user_data
ops/terraform/test.bluebutton.cms.gov/main.tf

Changes nginx's `resolver` directive to use Amazon DNS server. This should fix intermittent 'bad gateway' errors caused by DNS resolution timeouts.
Otherwise, I've included a few changes to fix error docs for the prod and test sites and change the behavior of the prod site to return a 404 instead of 403 when requested document is not found.

Fix for intermittent 'bad gateway' from nginx, other misc. changes

---

ops/terraform/bluebutton.cms.gov/templates/nginx.conf

This rule was not working properly because it was not configured match more than a single character in a path. This fix will ensure the nginx proxy fetches the correct `index.html` file for a given sub-page/path of the site. For example: `/developers/` will now properly proxy to the`/developers/index.html` object in the S3 bucket.

Fix rewrite rule for sub pages

---

_plugins/api_codings.rb

This allows us to (eventually) host other stuff under '/resources/' without having to worry about collisions.
https://issues.hhsdevcloud.us/browse/CBBI-343

CBBI-343: Codebook URLs now '/resources/variables/xxx'.

---

ops/terraform/bluebutton.cms.gov/main.tf
ops/terraform/bluebutton.cms.gov/templates/user_data

Following up on this. Ensures we're getting our nginx access and error logs into Splunk.

Make sure splunk is properly configured as new instances come up

---

_layouts/terms.html
_pages/developers.md
_pages/terms.md

@aviars Can you give the Terms and Developer Guidelines a quick read?  The Terms copy has not changed, just bringing into the new layout.  The Developer Guidelines page is new and will continue to improve after this first version.
We will need to update the link to the Terms in the Dev Portal / Register App view.

Terms and Developer Guidelines

---

_includes/header.html

Deleted <h5 class="sr-only" id="desktop-nav">Main site navigation</h5>` and the `aria-labelledby="desktop-nav"` from the <ul> beneath it, per 508 feedback on 2/27

508 changes

---

_pages/resources-codesystem-eob-type.md
assets/for-data-tables.scss

This is crucial because this is the field and code system that third-party devs need to disambiguate which EOB claim/event type they're looking at.
Note: this will be ugly-ish until PR #53 is merged.
https://issues.hhsdevcloud.us/browse/CBBF-97

CBBF-97: Document BBAPI's custom EOB.type code system

---

_pages/resources-codesystem-hcpcs.md

We're going to use this codesystem rather than `https://bluebutton.cms.gov/resources/variables/hcpcs_cd` so that we can provide a bit of extra documentation. Not a lot extra yet, but we may have more in the future, as this code system generates a **lot** of interest from developers.
Note: this will be ugly-ish until PR #53 is merged.
https://issues.hhsdevcloud.us/browse/CBBF-97

CBBF-97: Document the HCPCS code system

---

ops/terraform/bluebutton.cms.gov/main.tf

Change the names by adding `-static-` to differentiate these alarms from the ones configured for the API server.

Update autoscaling policy/alarm names

---

_config-prod.yml
_config-test.yml

Adding url to _config-prod and _config-test files to set to host name.
ONLY deploy to TEST for now.

CBBP-1058: BUG - fix jekyll site.url missing in test

---

_config-prod.yml
_config-test.yml
_config.yml
_includes/header.html
_layouts/category.html
_layouts/newest_blog.html
_layouts/post_with_category.html
blog/categories.html
blog/category/blog.html
blog/category/code.html
blog/category/general.html
blog/category/latest.html
blog/index.html
feed.xml

allows use of .html extension via parameter setting in _config-{env}.yml
This seems to be needed on S3 which wasn't finding .html files created by Jekyll.

Cbbp 1058 set dot html parameter

---

_config.yml

So this should do the trick to minify the `main.css` file in the Jekyll build. The only thing that is weird about this is that the minified CSS is not showing up as a change, even though I can verify locally that the CSS file is now minified. But I'm thinking that maybe this just happens in the build process?
It might be worth merging to test, but let me know if you have any questions or concerns about this.

Updates _config.yml to minify compiled CSS

---

.gitignore
package-lock.json

By telling the static site repo to ignore the CSS repo directory, I pull in the CSS repo for use as the CSS locally when making these changes.
This is step one of getting the CSS Repo up and running in the static site repo.

Updates gitignore to ignore CSS repo directory

---

_includes/head.html

When I initially merged these changes, I forgot to add the `relative_url` flag to make sure the path would work on all pages. This small change fixes that problem and should put us back in business!

486 - Fixes relative url issue linking the css

---

_layouts/post.html

So, this tries to organize the `post.html` a bit. Here is a summary of the changes:
- Moved the buttons below the title
- Spaced out the code a bit and added comments.
- Made the title in the banner a `<h1>` tag for accessibility reasons. We typically don't want to have an `<h3>` before a `<h1> ` tag. This means that some pages will have two `<h1>` tags, but we can fix that in a different issue.
- For now, I commented out the `Category` links. We have a ton of posts that are marked as `latest` that obviously aren't the latest. I think those can be cleaned up, it is just less confusing to remove them, especially since you can filter by them at the bottom of the page.
This is what the updated header looks like locally:

551 - Cleans up and fixes blog post header

---

assets/js/main.js

Since we don't have Babel in place yet, I just went ahead and reverted the one arrow function to a regular function to see if that will fix the problem with IE 11.
The problem is that when the "Menu" button is clicked, nothing happens.

616 Mobile Nav IE 11 Fix

---

_config-staging.yml
ops/Jenkinsfile

Summary: We want to build out a new STAGING environment for the BB 2.0 static site which needs to modify our parameterized deployment pipeline (test, staging, prod, etc.). I also bonused and added a scripting check for ruby versions installed to install our desired version is missing. Lastly, I added _config-staging.yml to the repo which is used to build the STAGING environment. 
- Jenksfile modified to include new STAGING options, build phase and deploy phase. 
- Jekyll staging config file
- Ruby check and install if not found (version 2.4.5)
I've tested this branch directly within the pipeline with no errors and successful push to the new S3 bucket:

642: Deploy: Check ruby version, staging deploy. Config: Add _config-staging

---

_pages/developers.md
_posts/2019-02-07-introducing-native-mobile-app-support.md

Now, in the blog post, when you click on the "Blue Button Documentation" link - you will be taken right to that section in the documentation.

BLUEBUTTON-736 - Adds anchor to blog post.

---

_layouts/support.html

This takes care of the static site portion of this ticket.

BLUEBUTTON-920 Removes references to Slack on the Support page

---

_pages/developers.md

As far as I can tell, this is just the one reference in the developer documentation. I tried `grep`-ing to find any additional references. There were a lot of references in the `_codebooks` and `ig`, but it didn't look like any of there mentioned the monthly refresh.
I'd love an additional pair of eyes to make sure, but I think this reference in the docs is definitely the most important.

BLUEBUTTON-1053 Remove all references to part D data being available monthly

---

ops/Jenkinsfile
ops/helpers.groovy

What: 
Add slack notices to static site pipeline job. 
Why:
So we can use a 'chatops' style of monitoring this job. 
How:
I've ported the slack notices pipeline syntax and the helper file to the static site repo and jenkins pipeline. Notices of start, success and failed are sent. Tested directly.

BLUEBUTTON-1610: Add slack notices for Static Site Pipeline

---

_posts/2019-12-16-bbapi-update.md

This update adds an announcement of our remediation status to the incident blog post to let publicly let apps know what needs to happen to get access again.

Adds status update to incident blog post

---

_pages/terms/2019-11-14-terms-of-service.md

Lori notified me of a redundant link in the ToS that was confusing someone from the CARIN Alliance. The solution was simply to remove the link to our documentation since we are already linking straight to the branding guidelines in the ToS.

BLUEBUTTON-1653

---

_pages/developers.md

For the error message:
```
Blue Button doesn't have any claims data for you just yet. Please try again later.
```
We added the following copy to the documentation:
`If Blue Button does not have data for a beneficiary, they will not be able to authorize access to the API, and will see the error message above.`

Adds context to error message about missing claims data

---

_pages/developers.md

This pull requests adds data that explains how an application can choose whether or not they want to collect demographic information from beneficiaries.
**Note: This work can be merged at any time, but should only be deployed once we have launched phase II of scopes in the Sandbox.**

BB2-185 P2 Scope: Update developer documentation for demographic data

---

_pages/developers.md

This is another pretty straight-forward change. In an effort to get users up-and-running as quickly as possible with our API, we've moved the "Try the API" section to the top. This will hopefully help ensure that:
- Users are able to quickly register an application
- Users can take their application credentials and test using a tool like Postman or cURL.
This update does not make any changes to the content of the documentation, simply its presentation order. This update is the first in a series of iterative updates to the developer documentation that will aim to make it more user-friendly for the users who consume it.

BB2-218 - Highlight the "Try the API" section of the developer documentation

---

README.md
_config.yml
_pages/blog.md
_pages/developers.md
_pages/eob.md
_pages/production-access-user-guide.md
_posts/2018-04-06-Welcome-to-the-Blue-Button-Blog.md
_posts/2018-05-04-Installing-a-Nodejs-client-application.md
_posts/2018-05-19-How-Beneficiaries-Authorize-an-App.md
_posts/2018-06-04-Installing-a-Django-client-application.md
_posts/2018-06-05-Speed-up-data-transfers.md
_posts/2018-06-07-Bluebutton-FHIR-Implementation-Guide.md
_posts/2018-06-15-Working-With-FHIR.md
_posts/2018-07-24-Delving-in-to-Blue-Button-Data.md
_posts/2018-10-09-BBDC18-Roadmap-Q-and-A.md
_posts/2018-12-18-Install-a-ruby-on-rails-client-app.md
_posts/2019-02-07-introducing-native-mobile-app-support.md
_posts/2019-11-13-giving-beneficiaries-more-granular-choice-of-data-sharing copy.md
_posts/2019-11-14-ensuring-beneficiary-privacy-and-security-through-new-application-onboarding-requirements.md
_posts/2020-02-11-check-out-updates-to-the-developer-documentation.md
blog/category/code.html
blog/category/general.html
blog/category/latest.html
blog/index.html
index.md
ops/README.md

**Context:**
Because there is an original "Blue Button" service where users can download a flat file of their claims data, we want to be sure all the copy on our static site to distinguishes the Blue Button 2.0 API from the original Blue Button service.
This PR has multiple commits of a lot of changes. I `"grepped"` several different ways to find all references. We essentially wanted to take any reference to `Blue Button` and ensure it said either `Blue Button 2.0` or `Blue Button 2.0 API`.

BB2-231 Update references to Blue Button on the static website
