CMSgov/bluebutton-site-static

ops/terraform/bluebutton.cms.gov/main.tf
ops/terraform/bluebutton.cms.gov/templates/nginx.conf
ops/terraform/bluebutton.cms.gov/templates/user_data

Simply making sure the nginx config is tracked in git.

Add the config used for nginx proxy

---

robots.txt

robots.txt file

---

assets/main.scss

sass optimized for responsive display, specifically for navigation and header elements on the iPad and mobile devices.

various sass changes

---

ops/Jenkinsfile

Fix formatting of hipchat success msg

---

_codebooks/codebook-mbsf-abcd-trimmed.xml
_config.yml

Not a huge deal, but I had used these fields in my demo, so they should probably be there for now.
https://issues.hhsdevcloud.us/browse/CBBI-314

CBBI-314: Included trimmed bene field data

---

_includes/header.html

Added aria-label tags for icons for 508 compliance

updated header to include aria labels for icons

---

_pages/developers.md

Small change. One piece of info was wrong.

Fix sample URL per Paul's comment

---

_pages/developers.md
index.md

@karlmdavis Can you take one more pass to verify the way we are providing an overview of the FHIR Data Model makes sense?

Added FHIR Data Model copy

---

_pages/developers.md

This is not fantastic, but I need to get these usernames and passwords on our site.

Add synthetic user info

---

_layouts/terms.html
_pages/developers.md
_pages/eob.md
_pages/terms.md
sample-eob-entry.json

Added a new Explanation of Benefits page at /eob, added a sample json file with Entry resource and a few minor changes to the Core Resources and FHIR Data Model sections.

Updates to core resources dev docs

---

_pages/developers.md

https://issues.hhsdevcloud.us/browse/CBBI-342

CBBI-342: Publish our data refresh schedule

---

_layouts/variable.html
_plugins/api_codings.rb

Couple minor tweaks to the layout for CCW variables. Most importantly: ensure that the Comment field is included.

CBBM-96: fix variable layout

---

_includes/header.html

508 changes that were lost from previous merge

508 changes

---

_includes/header.html
_includes/mobile-navigation.html
_pages/developers.md
_pages/eob.md
_pages/himss.md
_pages/terms.md
index.md

Take a look and see if you like the language. I'm less confident on this change than I thought I'd be.

Rename Sandbox and Fix Links

---

ops/terraform/bluebutton.cms.gov/main.tf

A little added protection for our proxy servers in the event that traffic flares up.

Add autoscaling policy for http proxy servers

---

_layouts/layout-for-data-tables.html
_layouts/variable.html

variable.html has updates for specifying specifics rows to apply styling
layout-for-data-tables needed for data-tables specific stylesheet

layouts for data tables

---

_layouts/variable.html

Looks like these fixes I'd made to the layout and PR #56 "passed in the night" and my changes got overwritten. No big -- just adding them back here.
CBBF-97

CBBF-97: Fix variables' fields

---

_includes/blue-button-logo.svg
_pages/developers.md
index.md

@rnagle, very minor copy tweaks.  This can go to prod whenever you're ready.

Copy tweaks

---

_pages/developers.md
sample-coverage-entry.json
sample-patient-entry.json

Updated sample output
Added two new sample json files

Updates to Patient and Coverage

---

_layouts/layout-for-data-tables.html
_layouts/variable.html
_pages/resources-identifier-claim-group.md
assets/for-data-tables.scss
assets/main.scss

Documenting one of the new API response URIs. **Please see commit comments for details.**

CBBF-97: Added docs for Claim Group ID

---

_pages/developers.md

Lucille is a hypothetic beneficiary that displays several examples of claims a lung cancer patient will have in their Explanation of Benefit FHIR resource.

Added Lucille

---

_includes/head.html

Added the CrazyEgg snippet to head to collect anonymous audience UX behavior for a week.

Install Crazyegg

---

_pages/developers.md

Copy bug fix

---

_includes/mobile-navigation.html

Seems to have dropped off in the PRs

fix blog item in menu for mobile-nav

---

_includes/mobile-navigation.html
assets/ig/index.html

Fix duplicate entries in mobile menu
fix conflict in IG index.html to clean up top of IG page

Fix minor issues

---

_posts/2018-05-04-Installing-a-Nodejs-client-application.md

change line in Blog post from:
node app.js -t localhost -p 8001
to 
node app.js -t http://localhost -p 8001

BLUEBUTTON-385: fix load command for node app to add http://

---

_posts/2018-08-08-More-Sample-Applications.md

Add sample applications blog post

BLUEBUTTON-393:more sample applications blog post

---

_posts/2018-10-09-BBDC18-Roadmap-Q-and-A.md

Missed this in the initial check.

Tweak one question to match approval document

---

_layouts/default.html

Pretty simple - it is actually just one line of HTML... so I will have to let Christian know. :wink: 
All kidding aside, I think this is all it takes.

Adds tracking script to static site

---

_posts/2018-04-06-Welcome-to-the-Blue-Button-Blog.md
_posts/2018-04-13-Sample-Applications.md
_posts/2018-05-04-Installing-a-Nodejs-client-application.md
_posts/2018-05-19-How-Beneficiaries-Authorize-an-App.md
_posts/2018-06-04-Installing-a-Django-client-application.md
_posts/2018-06-05-Speed-up-data-transfers.md
_posts/2018-06-07-Bluebutton-FHIR-Implementation-Guide.md
_posts/2018-06-15-Working-With-FHIR.md
_posts/2018-07-24-Delving-in-to-Blue-Button-Data.md
_posts/2018-07-31-Update-to-Developer-Docs.md
_posts/2018-08-08-More-Sample-Applications.md
_posts/2018-08-30-Install-a-Spring-Boot-Client-App.md
_posts/2018-10-09-BBDC18-Roadmap-Q-and-A.md
_posts/2018-10-17-Install-an-Angular-Client-App.md
_posts/2018-10-24-Install-a-Ruby-on-Rails-Client-App.md

So, @cgreim caught that there were some irregularities with blog posts. One thing she found was inconsistencies with the badge text. I have updated every post so that the badge will display as "Blog."
Additionally, I noticed an accessibility issue and bug with the posts where the `h1` title was duplicated in the actual post. I have corrected this so that there will only be one `h1` tag and that the titles are all consistent with the post.

551 - Fixes inconsistencies with Blog posts.

---

_config.yml
_includes/header.html
_layouts/default.html
_sass/_nav.scss
assets/js/main.js

So, I think this may be ready to deploy to test, along with the update to the CSS Repo. This will give me some time to look at it in a real environment, on various phones, etc.
List of changes/tweaks:
- HTML changes are pretty self-explanatory, but I consolidated where I could, cleaned up the logo SVG, added comments, etc.
- Implemented [Feather Icons](https://feathericons.com). They are open source and super easy and fun to work with. I used them in the design approval, so I needed them here. Can slowly phase out other icons in the future to reduce load.
- Wrote nav logic in vanilla JS to eventually reduce our dependence on jQuery, which we could remove in the future for a potential performance win/stay up with the times.

560 Update the Static Site Navigation

---

_includes/banner.html
_layouts/bbdc.html
_layouts/bbdcv2.html
_layouts/category.html
_layouts/developers.html
_layouts/home.html
_layouts/newest_blog.html
_layouts/post.html
_layouts/post_with_category.html
_layouts/post_with_category2.html
_layouts/terms.html
_pages/blog.md
_pages/developers.md
blog/categories.html

This PR makes the banner that was there a component, changes aspects of the banner HTML, and implements it across the site. I clicked through everything I could find and I think I updated it in all instances.
This is dependent on [this PR from the CSS Repo](https://github.com/CMSgov/bluebutton-css/pull/23).

BLUEBUTTON 434 - Fix static site banner

---

_pages/developers.md
_posts/2019-02-07-introducing-native-mobile-app-support.md

The first part of this is the blog post. 
The second part of this is the documentation update. Take a look and make sure this all looks good.

BLUEBUTTON-736 - Adds native app blog post and documentation update

---

_posts/2019-03-15-more-frequent-prescription-data-updates.md

Here is the blog post that leadership wants up on Monday at 11am.

Adds blog post for review

---

_posts/2019-03-15-more-frequent-prescription-data-updates.md

Removes the whitespace for this PR.

Prescription data updates blog post

---

_posts/2019-04-12-list-of-production-apps-approved-with-blue-button.md

Below is the blog post. Let's go ahead and let it rip to staging and go from there.

Adds emergency blog post

---

_config.yml

I think this would get us functionality back. Please review and let me know if we need to make any changes.

Codebooks Issue - Uncomments the needed XML files

---

_includes/head-for-data-tables.html
_layouts/layout-for-data-tables.html

This adds the CSS file we are using on the static site. I think there is an opportunity in the future for me to bring these pages into the fold and make them more in line with our overall styles, but I think this is good enough for now!

Adds CSS and minimal styles ro resources documentation

---

_codebooks/codebook-mbsf-abcd.xml
_config.yml

Let me know if there is anything else that needs to be done here.

BLUEBUTTON-976 Adds codebook file and updates config

---

package-lock.json

Really simple security fix for the mem dependency that GitHub identified.

Security: Updates mem dependencies

---

_pages/developers.md
_posts/2018-06-05-Speed-up-data-transfers.md

I have tested against sandbox to ensure gzip compression works.
I have updated references to application/json+fhir to application/fhir+json (however both work).
I also added an example section to developers.md

clarify compression instructions

---

_pages/developers.md
_pages/production-access-checklist.md
_pages/production-access-user-guide.md
_pages/terms/2019-11-14-terms-of-service.md
_pages/terms/index.md
_posts/2019-11-13-giving-beneficiaries-more-granular-choice-of-data-sharing copy.md
_posts/2019-11-14-ensuring-beneficiary-privacy-and-security-through-new-application-onboarding-requirements.md
index.md

I think this fixes most of the issues with the new ToS deploy.

Adds a bunch of fixes for issues discovered during testing

---

index.md

A simple typo was discovered in test review - this change simply fixes that typo for release.

Fixes typo found in TEST review of Coms Update

---

_posts/2019-12-16-bbapi-update.md

This provides a slight update to our technical blog post about the Blue Button 2.0 API.

Blue Button API Update: Updates impacted app count and adds list of apps

---

_posts/2019-12-16-bbapi-update.md

Corrects an application name in the communication materials.

Blue Button 2.0 API Update: Corrects application name

---

_posts/2019-12-16-bbapi-update.md
index.md

Updates copy based on input from leadership. No immediate rush to review/approve this PR. Getting it up so we are ready to go on Thursday.

Final coms update to the update blog post

---

_pages/developers.md

Upon review of this change, we discovered several small typos this PR seeks to fix.

"Try the API" Corrections for Release

---

_pages/developers.md

There were a few final changes requested to the documentation updates and blog post before deploying to production.
I am waiting on final confirmation/any additional changes and will update this PR when I hear back.

Leadership's Requested Changes to Docs/Blog Post

---

_pages/developers.md

This PR removes incorrect information from our documentation around a specific error message.

BLUEBUTTON-1926

---

package-lock.json

These are a few dependencies that Github detected vulnerabilities for, but that it couldn't generate automated PRs for (for some reason). 
So I've manually updated the dependencies, which should alleviate the security concerns.

Security Fixes: Dependency Updates

---

_pages/developers.md

Here are the implemented documentation updates. Does the placement under "Core Resources" make sense?
Any other feedback welcome and appreciated.

BLUEBUTTON-1936 Update static site documentation for _lastUpdated and Query by Type

---

_pages/production-access-user-guide.md

In the past, we've had confusion with some of our third-party partners around what to expect in the in-person demo during the production access process.
We're adding some guidance to our production access user guide in the hopes that this will reduce confusion around things that we'd like to see in that meeting with applications.

BB2-215 - Production Access Demo Information Sharing

---

_posts/2019-11-13-giving-beneficiaries-more-granular-choice-of-data-sharing copy.md

As part of our communication strategy for the release of scopes work, we are updating the original announcement blog post in order  to add a note that the feature is now live in production.

BB2-256 - Scopes Ph1 Release Comms

---

_includes/footer.html

BB2-299 SSP TR-01(1) - Add Privacy Policy Link to Static Site

---

_pages/developers.md
_posts/2020-07-29-get-just-the-claims-data-you-need.md

While reviewing a blog post to deploy, stakeholders identified two updates they wanted us to make.

Updates date format and adds outpatient to list

---

index.md

Updates homepage copy in banner and overview section to more accurately reflect the purpose/scope of the API.

BB2-332: Updates overview and banner text

---

Dockerfile
README.md
docker-compose.yml

[BB2-400](https://jira.cms.gov/browse/BB2-400)
This adds a dockerized setup for local development per James's work in [BB2-402](https://jira.cms.gov/browse/BB2-402).
This should make it easier to develop across platforms (Linux/Mac/Win).
The following was added or changed:
* Added `Dockerfile` and `docker-compose.yml` files for dockerizing the setup.
* Added a "Dockerized Setup" section to the README.md document.
* Are there any unhandled and/or untested edge cases you can think of?
* Does this make any backwards-incompatible changes that might break end user clients?
* Can you find any bugs if you run the code locally and test it manually?
* Naming in general? Do the …

BB2-400 Update/Dockerize local development setup

---

ops/Dockerfile.cbc-build
ops/Jenkinsfile.cbc-build-deploy
ops/cbc-build-push.sh
ops/cbc-build.yaml
ops/helpers.groovy

[BB2-409](https://jira.cms.gov/browse/BB2-409)
Migrate the following jobs to CB Core:
- DEPLOY - Static Site
- Defines and automates the build of a docker container suitable static site build and deploy
- Defines a Kubernetes pod for use in CB Core
- Rewrite the build and deploy job for simplification and parameterization per environment, just like our AMI deploys.  No more "all environments at once" job.
- This adds extra time to each build because gem/bundle components aren't shared between environments, but I believe this is worth the trade-off in terms of simplicity in logic.
- Did I break anything that used to work?
- Did I miss porting over some vital feature?
- …

BB2-409: Migrate build/deploy Jenkins job to CloudBees Core

---

ops/Jenkinsfile.cbc-build-deploy

Fixing a major goof for the CBC migration PR #225.  Must have happened when I copied this code from the web server repo.  🤦

BB2-406: Add missing brackets to fix Jenkinsfile syntax error

---

.github/pull_request_template.md

[BB2-440](https://jira.cms.gov/browse/BB2-440)
As a BB2 team, it is necessary to have the DASG CoP standardized PR template in all of our repositories.
The following is a list of changes from the commits:
* This installs the DASG based Github PR template in to .github/pull_request_template.md
* Are there any edits and/or additions needed to the template related use in this repository?
* Does this PR add any new software …

BB2-440 Add PR template to repository

---

_pages/developers.md

[BB2-411](https://jira.cms.gov/browse/BB2-411)
Fix typo in developer documentation
As a developer, I want to see a typo in the developer documentation fixed to avoid any potential confusion.
Removes unneeded characters and makes the first line a bullet point as intended
* Spelling mistake
* Missed characters
* Does this PR modify or invalidate any of our security …

Rouge character was stopping bullet list

---

_pages/developers.md
_posts/2018-05-19-How-Beneficiaries-Authorize-an-App.md

[BB2-456](https://jira.cms.gov/browse/BB2-456)
As a user of bluebutton.cms.gov, I want to have a clear understanding of how and where users will authenticate to authorize access to BB2. 
With the rollout of SLSx, CMS will update the log-in URL for MyMedicare.gov so that it falls under the Medicare.gov domain. CMS also will shift how it refers to beneficiary-authenticated Medicare accounts to avoid referencing “MyMedicare.gov.” CMS is updating its messaging to use the core phrase “your Medicare account” for public-facing communications.
Markdown changes on developer docs and a previous blog post.
Spelling mistakes
* TODO
Submitters should complete the following …

Update references to myMedicare.gov

---

ops/Jenkinsfile.cbc-build-deploy

[BB2-473](https://jira.cms.gov/browse/BB2-473)
As a static site developer, it would be very useful to be able to deploy branches to different environments, and in particular auto deployment to test on PR submission would add a default integration testing for the static site repo. The Jenkins pipeline already supports this, we just need to add some protection to ensure that no one can accidentally deploy an unmerged branch to prod.
This PR adds a prod deployment gate to the Jenkins job that allows us to safely enable multibranch deplyments with scheduled run, which will greatly benefit the ease of testing PRs and branches against lower environments.  The conditions required for a prod deploy to succeed are set as follows:
- Must be run …

BB2-473: Safely support multibranch deployment

---

ops/Jenkinsfile.cbc-build-deploy

[BB2-473](https://jira.cms.gov/browse/BB2-473)
[JENKINS-41929](https://issues.jenkins.io/browse/JENKINS-41929)
Jenkins does not convert parameter to environment variable on first build
After merging #231 and setting up the final multibranch pipeline, I discovered builds will break on first build after scanning the repository 🤦 .  This is due to https://issues.jenkins.io/browse/JENKINS-41929, and the fact that I was using an implicit environment variable from a parameter. This just makes that parameter explicit.
N/A
* If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document …

BB2-473: Fix first build Jenkins bug

---

_includes/bluebutton-ig/header.html
_layouts/default-full.html
_layouts/default.html

[BB2-053](https://jira.cms.gov/browse/BB2-503)
As a front-end engineer, I want to improve the performance of our static site
Removes the CrazyEgg JS lib
* JS lib or dependency errors
* Does this PR add any new software dependencies?  **No**.
* If the answer to any …

Remove Crazy Egg

---

_pages/developers.md

https://jira.cms.gov/browse/BB2-604
Better documentation on how to implement the PKCE Extension so that I can implement the promoted feature
NOTE: 6/10/2021 The changes from the following PR has been merged in to this one and has been closed:  https://github.com/CMSgov/bluebutton-site-static/pull/240#
1. Removes documentation to implicit flow since we no longer support it
2. Removes the "Mobile Support PKCE" section, we don't support a non-backend flow and that was only creating more confusion for users
3. Add in a new PKCE section with a code example, along with request templates
4. Added in a message in the normal OAuth flow section saying that using PKCE is now recommended
5. Added PKCE to the postman example
- Make sure there are no …

[ BB2-604 ] Removing implicit flow docs. Adding PKCE docs

---

_pages/developers.md

[SOMEPROJECT-42](https://jira.cms.gov/browse/SOMEPROJECT-42)
Fixes a broken anchor link to https://bluebutton.cms.gov/developers/#client-application-flow
* TODO
* Does this PR store or transmit data that was not stored or transmitted before?  **No**.
* If the answer to any of the questions below …

Fix broken anchor link to #client-application-flow

---

_pages/developers.md

took the stray "S" out of the bold format to indicate the synthetic bene password
[SOMEPROJECT-42](https://jira.cms.gov/browse/SOMEPROJECT-42)
Take a stray "S" out of bold formatting to indicate the synthetic bene password
* TODO
* Does this PR store or transmit data that was not stored or …

remove stray S from bold format

---

_posts/2019-04-12-list-of-production-apps-approved-with-blue-button.md

[BB2-871](https://jira.cms.gov/browse/BB2-871)
Update broken and non-redirected links across the static site + BB2
Across our static site and blog, there may be former medicare.gov links that are no longer working. examples of this include:
https://bluebutton.cms.gov/blog/list-of-production-apps-approved-with-blue-button.html linking to http://go.cms.gov/bluebuttonapps
Misspellings 
* Does this PR add any new software dependencies? **No**
* Does this PR modify or invalidate any of our security …

Correcting apps link

---

_pages/developers.md

Removes some unintended stray feedback questions from the Developers page
Check bullet formatting to ensure it doesn't break HTML
None
* Does this PR store or transmit data that was not stored or transmitted before? **Yes** or **No**.
* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR should not be merged unless/until he …

Remove feedback questions from Developers page

---

README.md
_config.yml
_data/rda_api_data_dictionary.csv
_layouts/rda_api_variable.html
_plugins/rda_api_variables.rb

[PACA-733](https://jira.cms.gov/browse/PACA-733)
Add tooling to automate the creation of coding system descriptions in the BB2 static website.
Follows the conventions established for generating pages for CCW codebook variables to generate similar pages for FISS and MCS claims from the RDA API data dictionary.
- Adds a generator plugin to process records from the data dictionary and produce one page per record.
- Adds a layout file to render the pages.
- Adds a CSV file to `_data` containing the RDA API data dictionary records to render.
- Adds commented out sample configuration to `_config.yaml`.
* Does this follow conventions.
* Is there more to be done to properly …

PACA-733: RDA API data dictionary plugin.

---

_config.yml
_plugins/rda_api_variables.rb

[PACA-733](https://jira.cms.gov/browse/PACA-733)
This PR fixes a naming conflict between the RDA and BFD variable page generator plugins.  With this change in place and the relevant sections of the _config.yml file uncommented both are able to generate their variable pages without conflicts.
* n/a
* Does this PR add any new software dependencies?  **No**.
* Does this PR modify or invalidate any of our security controls? …

PACA-733: Fixes naming conflict between the RDA and BFD plugins

---

_includes/header.html
_includes/swimlanes.html
_includes/value-for-benes.html
_includes/value-for-orgs.html
_layouts/support.html
_pages/production-access-user-guide.md
_posts/2020-07-29-get-just-the-claims-data-you-need.md

[BB2-1305](https://jira.cms.gov/browse/BB2-1305)
CMS has a website requirement that we show the USA banner at the top of all government supported sites. We need to add new website banner design as given by CMS.  Documentation can be found here: https://design.cms.gov/components/usa-banner/
Banner should be added to the static site on all pages. Also, it should be added to the sandbox after sign-in on all pages.
AC:
1. Add banner to static site 
2. Verify it shows on all pages
Added US Banner html fragment (section) to the header.html so that US Banner gov site top will appear in BB2 static site web pages.
Note, the US Banner html fragment is derived from CMS Design system (USA Banner component)
**Note, the BB2 CSS part of the static site …

[BB2-1305] Added US banner on top of bb2 static site (a CMS gov site) pages

---

Gemfile.lock

[BB2-1792](https://jira.cms.gov/browse/BB2-1792)
Nokogiri has a high vulnerability in the static code base.  This ticket is to make the recommended upgrade from 1.13.6 to 1.13.9
Update nokogiri to recommended version.
* If the answer to any of the questions below is **Yes**, …

BB2-1792 Update nokogiri to 1.13.9

---

_pages/terms/2022-11-01-terms-of-service.md
_pages/terms/index.md

[BB2-1770](https://jira.cms.gov/browse/BB2-1770)
*Description:*
We currently don't mention anything about the medicare.gov terms of service in our API TOS, even though our API relies on Medicare.gov logins. We have drafted an update to the TOS that includes information about how using our API also implies acceptance of the Medicare.gov terms.  The update includes 2 changes. The changes are described in the comments on [this Confluence page|[https://confluence.cms.gov/x/BgfoKg]]. 
*User Story:*
As a developer/product manager/CEO from a healthcare organization, I want to understand how Medicare.gov terms of service relate to implementing and using the Blue Button API, so that I am not blocked from accessing the prod environment and data. …

[BB2-1770] Update Blue Button API Terms of Service

---

_pages/terms/2019-11-14-terms-of-service.md
ops/cbc-build-push.sh
ops/cbc-build.yaml

[BB2-1942](https://jira.cms.gov/browse/bb2-1942)
- Update ruby build version to match local docker version
- Add trailing slash to terms/v2/ path
Build container is now aligned with the same Ruby version 3.1.2 for both the local docker development container.
The path for the archived terms/v2/ path is updated with a trailing slash to serve the page without a 404 error.
* TODO
* Does this PR add any new software dependencies? …

Bb2 1937 upgrade build contianer to ruby 3.1.2

---

_includes/swimlanes.html
_includes/value-for-benes.html

[BB2-1960](https://jira.cms.gov/browse/BB2-1960)
2 links on our website [https://bluebutton.cms.gov/] lead to a broken page due to Medicare.gov updating the URL. We need to fix this so it goes to the correct URL
*Acceptance Criteria:* 
- 1) The tile/link titled '[GET BLUE BUTTON DETAILS ON MEDICARE.GOV |https://www.medicare.gov/manage-your-health/medicares-blue-button-blue-button-20]" on bluebutton.cms.gov  should lead to this URL: [https://www.medicare.gov/manage-your-health/medicares-blue-button-blue-button-20/blue-button-apps]
 
- 2) The button "[What's the Medicare Blue Button|https://www.medicare.gov/manage-your-health/medicares-blue-button-blue-button-20]" on this page: [https://bluebutton.cms.gov/#Value_for_orgs] is broken. It should …

[BB2-1960] Fix medicare.gov BB2 Apps page links on static site home page

---

Gemfile
Gemfile.lock

[BB2-1935](https://jira.cms.gov/browse/BB2-1935)
Per security audit and SNYK report:
There is 1 high vuln!
There is 1 high level vuln in bluebutton-site-staic
SNYK PR CREATED: https://github.com/CMSgov/bluebutton-site-static/pull/284
SNYK LINK:  https://app.snyk.io/org/bluebutton-oeda/project/1d8b6f04-cbde-4b07-8f90-0156c3755805
Bump nokogiri version from 1.13.9 to 1.13.10 to mediate high vulnerabilities.
1. nokogiri upgraded to 1.13.10
2. the site static functions as expected
* TODO
* If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact Assessment (SIA), …

[BB2-1935] SNYK Security upgrade nokogiri from 1.13.9 to 1.13.10 to mediate high vulns

---

_pages/resources.md

[BB2-1955](https://jira.cms.gov/browse/BB2-1955)
The FTC has a website that explains privacy and security considerations for healthcare apps, especially those that collect and share consumers health information.  
A link to the website should be available from the static site Resources page.  
Website: https://www.ftc.gov/business-guidance/resources/mobile-health-apps-interactive-tool
AC:
add the link to the "Tutorials & Learning Resources" section on the Resource page
QA:
Check that the post shows on the static site Resource page 
1. In Chrome
2. In Safari
3. In Firefox
4. In Edge
5. On a mobile device
Added FTC Mobile Health App Interactive Tools page to BB2 site resources page: in tutorial section
Verify that the said FTC link added to …

[BB2-1955] Add FTC Mobile Health App Interactive Tool page to BB2 Resource page

---

docker-compose.selenium.yml
run_selenium_tests.sh
selenium_tests/Dockerfile
selenium_tests/src/test_site_static.py

[BB2-1764](https://jira.cms.gov/browse/BB2-1764)
Description:
BB2 web pages (SBX and site static etc) are government sites, there are requirements for certain compliances at gov sites level - e.g. USA banner at the top with unified look and feel, across Organization compliances requirements, e.g. standard text and links across HHS, or CMS etc.
Automated selenium tests are a good pick to perform the monitoring of all the compliances required on BB2 web UI.
Implementation note:
Current BB2 selenium tests traversal some of the SBX web pages, we can extend the tests so that the web UI widgets and texts and links are checked for their present
If necessary, we can also add selenium tests navigating and traversal site static pages and checking the …

[BB2-1764] Added selenium tests cover gov site banner and CMS footer compliances

---

_includes/footer.html

[BB2-2118 ](https://jira.cms.gov/browse/BB2-2118 )
Add terms of service link to footer.  It appears under "Documentation" in the "Blue Button 2.0 API" column.
Make sure the link appears the same as others in the footer and takes you to the terms of service page.
* Does this PR modify or invalidate any of our security controls?  **No**.
* Does this PR store or transmit …

BB2-2118 Add Terms of Service to Website Footer

---

_includes/footer.html
_includes/header.html
_includes/swimlanes.html
_includes/value-for-benes.html
_layouts/support.html
_pages/developers.md
_pages/resources.md
_pages/terms/2022-11-01-terms-of-service.md
_pages/v1.md
_pages/v2.md
selenium_tests/src/test_site_static.py

[BB2-2117](https://jira.cms.gov/browse/BB2-2117)
External links should open in new tabs.  Most of these are found on the resources page and in the footer.
Make sure external links open in new tab.  Sandbox links also open in new tabs.
* Does this PR modify or invalidate any of our security controls?**No**.
* If the answer to any of the questions below …

BB2-2117 Make external links open in a new tab

---

_pages/developers.md

[BB2-2117](https://jira.cms.gov/browse/BB2-2117)
Fix bundle links in developers documentation to open in a new tab.
Fix FHIRv4.3 link to open in a new tab
Remove 'localhost' link.
* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, …

BB2-2117 More links fixed after QA

---

_pages/developers.md

[BB2-2169](https://jira.cms.gov/browse/BB2-2169)
The heading structure on the static site documentation does not adhere to best practices for writing for the web or accessibility. Formatting issues cause the page to be difficult to scan.
- The top-level headings are h3s and should be h2s
- Subheadings should be nested under h2s
- Bolded text is used instead of headings in several places
- Bolded text is used too much, causing visual clutter and making the content hierarchy difficult to decipher at-a-glance
- Code formatting is not used in places where it should be
- Numbered lists in the "Try the API" section have padding issues, formatting issues, and restart their numbering partway through
- Images have inconsistent padding
- Fixes heading …

BB2-2169-documentation-heading-hierarchy-and-formatting-updates

---

ops/Jenkinsfile.cbc-build-deploy-akamai

[BB2-2228](https://jira.cms.gov/browse/BB2-2228)
The static site deployment has been updated with this ticket so that it is deployed to NetStorage. Also remove the previous S3 method from the Jenkinsfile.
Review the console output under DEPLOY - Static Site (Akamai) Jenkins job -> PR's -> Pull Request PR-304 -> Console logs
If you want to see the files on NetStorage, download the SFTP keys from secrets manager, and make a connection with SFTP tool of choice. Run the ls command, and cd into the only directory available in the root, then you will see the test.static.bluebutton.cms.gov directory which you can cd to view the files.
Last, while connected to cloud VPN on CMS, take a look at the site. You should also see that traffic is blocked …

[ BB2-2228 ] Update test static deploy to NetStorage 

---

_data/rda_api_data_dictionary.csv
_plugins/rda_api_variables.rb

[PACA-753](https://jira.cms.gov/browse/PACA-753)
The PACA FHIR mappings need to be updated on BB2.0 after review by the FHIR SME for the data expansion.
Notes: 
- https://jira.cms.gov/browse/PACA-733
- https://github.com/CMSgov/bluebutton-site-static/pull/270
- https://github.com/CMSgov/bluebutton-site-static/pull/271
- Updates the `rda_api_variables.rb` plugin to skip incomplete/blank rows in the spreadsheet.
- Updates the `rda_api_data_dictionary.csv` spreadsheet with the latest version from RDA API.
* Site comes up with the change in place and variable pages are generated for FISS and MCS.
* If the answer to any …

PACA-753: Updates RDA data dictionary variables

---

_pages/developers.md

[BB2-2296](https://jira.cms.gov/browse/BB2-2296)
Our static site documentation gives both V1 and V2 code sample examples. Since we have separate v1 documentation that we link to, we'd like to remove V1 references in the V2 documentation.
Also, the DASG style guide says that shortened references to versions should be written as "V1" and "V2" not "v1" and "v2." We aren't consistent in our formatting of this and should update to adhere to the style guide.
- removed V1 code samples from static site documentation
- updates references to v1 and v2 to V1 and V2 to adhere to the DASG style guide
* formatting errors
* code sample accuracy
Submitters should complete the following …

BB2 2296 remove v1 code samples from documentation

---

_pages/developers.md

[BB2-2234](https://jira.cms.gov/browse/BB2-2234)
Fix FHIR url link for patient resource on developers page.
* Check that the link works
* Does this PR modify or invalidate any of our security controls? e**No**.
* Does this PR store or transmit data that was not stored or transmitted before?**No**.
* If the answer to any of the questions below is **Yes**, then please …

BB2-2234 fixes for core resources section

---

_pages/developers.md

Adds new Overview section to static site documentation
[BB2-2380](https://jira.cms.gov/browse/BB2-2380)
New high-level overview targeted toward a general audience, with some awareness of API technology, Medicare, and FHIR. Goal of section is to help the reader quickly learn what the Blue Button API is within 2 minutes. 
- Publishes Overview section
- Removes "This is the FHIR R4 (v2) documentation for the Blue Button API." information panel from the beginning of the documentation (this has been replaced by a link to V1 documentation under the Versions subheading in the new Overview section.
* Make sure there's a working overview link in the left navigation
* Review …

BB2-2380 - New Documentation Overview Section

---

_pages/resources-codesystem-identifier-currency.md

[BFD-2568](https://jira.cms.gov/browse/BFD-2568)
As a BFD user, I want https://bluebutton.cms.gov/resources/codesystem/identifier-currency to resolve so that I can learn more about the identifier-currency coding system.
This is one of several tickets involved with BFD's ability to serve URLs that resolve pertaining to the blue button static site. 
In this ticket, the focus is the identifier currency page.
A markdown file was added so that a new page can be autogenerated and deployed.
* Does this page conform to the content standards and adequately describe the resource in question?
* If the answer to any of the …

BFD-2568: Identifier Currency Page Resolution

---

_pages/developers.md

Updated Authorization section with new up-to-date content
[BB2-2241](https://jira.cms.gov/browse/BB2-2241)
Updated version of current Authorization section for developers integrating with BB2.0 API.
* Updates Authorization section content
* Removes Beneficiary Revoking Access subheading and content under Developer guidelines
* 
* Verify that all code samples in the Authorization section are formatted properly and are accurate
* Links: 
* check that all links in Authorization section work
* check that external links open in new tab
* check that internal links stay in new tab
* Tables in the Authorization section should be formatted properly--like the other tables in the …

BB2 2241 Update developers.md with new Authorization section content

---

_layouts/support.html
_pages/support.md

[BB2-2390](https://jira.cms.gov/browse/BB2-2390)
Our current [Support](https://bluebutton.cms.gov/support/) directs people to reach out to us on Twitter, but we're not monitoring Twitter for questions. We also don't include the Blue Button email address or offer any information about what types of requests to submit where or set any expectation for response turnaround times.
- Removes text below “Developer Support” in the hero banner/header. (Eventually, I’d like to redesign the whole banner and replace it with something that takes up less vertical space.)
- Edits subheading and text describing Google Group.
- Adds a Contact Us subheading with a description that links to the Blue Button email address
- Adds a turnaround time of 3 days.
- …

BB2-2390 Support page updates

---

_pages/developers.md

Adds EOB resource download link and moves Coverage resource link to the right spot.
[BB2-2452](https://jira.cms.gov/browse/BB2-2452)
In the [Core Resources](https://bluebutton.cms.gov/developers/#core-resources) section:
- we're missing a download link for an EOB resource code sample: https://bluebutton.cms.gov/sample-eob-entry.json
- the Coverage resource sample code download is in the wrong place
USER STORY 
As a technical decision-maker or builder, I want to see sample code for each of the FHIR resources available through the BB2.0 API so I can explore data points and learn about the data structure.
* Adds link to FHIR EOB resource JSON download
* Moves Coverage resource link to correct location, under the Coverage resource code sample
If …

BB2-2452 update developers.md - FHIR resources code sample download fixes

---

_pages/developers.md

small grammar fix
[BB2-2461](https://jira.cms.gov/browse/BB2-2461)
Changes "a" to "an" in one sentence
* Does this PR modify or invalidate any of our security controls?  **No**.
* Does this PR store or transmit data that was not stored or transmitted before?  **No**.
* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and …

BB2-2461 small grammar fix to developers.md

---

_pages/resources-codesystem-diagnosis-type.md

[BFD-2369](https://jira.cms.gov/browse/BFD-2369)
As a BFD user, I want https://bluebutton.cms.gov/resources/codesystem/diagnosis-type to resolve so that I can learn more about the diagnosis type coding system.
This is one of several tickets involved with BFD's ability to serve URLs that resolve pertaining to the blue button static site. 
In this ticket, the focus is the diagnosis type page.
A markdown file was added so that a new page can be autogenerated and deployed.
* Does this page conform to the content standards and adequately describe the resource in question?
* If the answer to any of the questions below is …

BFD-2369: Diagnosis Type Page Resolution

---

_pages/resources-codesystem-information.md

[BFD-2640](https://jira.cms.gov/browse/BFD-2640)
As a BFD user, I want https://bluebutton.cms.gov/resources/codesystem/information to resolve so that I can learn more about the information coding system.
This is one of several tickets involved with BFD's ability to serve URLs that resolve pertaining to the blue button static site. 
In this ticket, the focus is the information page.
A markdown file was added so that a new page can be autogenerated and deployed.
* Does this page conform to the content standards and adequately describe the resource in question?
* If the answer to any of the questions below is **Yes**, …

BFD-2640: Information Page Resolution

---

_pages/resources-identifier-hicn-hash.md
_pages/resources-identifier-mbi-hash.md

[BFD-2642](https://jira.cms.gov/browse/BFD-2642)
[BFD-2643](https://jira.cms.gov/browse/BFD-2643)
As a BFD user, 
1. I want https://bluebutton.cms.gov/resources/identifier/mbi-hash to resolve so that I can learn more about the mbi-hash identifier .
2. As a BFD user, I want https://bluebutton.cms.gov/resources/identifier/hicn-hash to resolve so that I can learn more about the hicn-hash identifier.
1. Adds Documentation for both the MBI_Hash and HICN_hash in the`bluebutton/bluebutton-site-static/_pages` directory. 
- Documentation
* If the answer to any of the questions below is **Yes**, then here's a link to the …

BFD2642_2643-Added documentation for both mbi and hicn hash

---

_pages/resources-codesystem-identifier-currency.md

[BFD-2758](https://jira.cms.gov/browse/BFD-2758)
As a BFD user, I want https://bluebutton.cms.gov/resources/codesystem/identifier-currency to resolve with the table of values section of the page formatted properly.
Update formatting of identifier currency page, specifically the values table section.
Is the page properly formatted with the new updates?
* Does …

BFD-2758: Fix Identifier Currency Page Formatting 

---

_pages/resources-codesystem-adjudication.md
_pages/resources-identifier-claim-group.md

[BFD-2637](https://jira.cms.gov/browse/BFD-2637)
[BFD-2641](https://jira.cms.gov/browse/BFD-2641)
- As a BFD user, I want https://bluebutton.cms.gov/resources/codesystem/adjudication to resolve so that I can learn more about the adjudication coding system.
- As a BFD user, I want https://bluebutton.cms.gov/resources/identifier/claim-group to resolve so that I can learn more about the claim-group identifier.
* TODO
* Does this …

BFD 2641_2637- publish identifier claim group and adjudication documentation 

---

_pages/resources-variables-fi_orig_clm_cntl_num.md

[BFD-2763](https://jira.cms.gov/browse/BFD-2763)
As a BFD user, I want https://bluebutton.cms.gov/resources/variables/fi_orig_clm_cntl_num -type to resolve so that I can learn more about the fi_orig_clm_cntl_num variable.
This is one of several tickets involved with BFD's ability to serve URLs that resolve pertaining to the blue button static site. 
In this ticket, the focus is the fi_orig_clm_cntl_num page.
A markdown file was added so that a new page can be autogenerated and deployed.
* Does this page conform to the content standards and adequately describe the resource in question?
* If the answer to any of the …

BFD-2763: Add Fi_orig_clm_cntl_num Page To Blue-button Static Site

---

_pages/resources-variables-nch_clm_prvdr_pmt_amt.md

[BFD-2764](https://jira.cms.gov/browse/BFD-2764)
1. As a BFD user, I want https://bluebutton.cms.gov/resources/variables/nch_clm_prvdr_pmt_amt to resolve so that I can learn more about the diagnosis-type coding system.
1.  Adds Documentation for NCH Claim Provider Payment Amount in Blue Button
* Documentation
* Does this PR add any new software dependencies?  **No**.
* Does this PR modify or invalidate any of our security …

BFD-2764: Added Documentation for NCH Claim Provider Payment Amount

---

_layouts/support.html
_pages/developers.md

Added Understanding the data and Optimizing your application. Removed several sections that are out of date, not useful, or replaced by new content. Fixed small mistakes.
[BB2-2528](https://jira.cms.gov/browse/BB2-2528)
Sections removed (and the links to these sections are removed from the left-hand navigation):
- Core Resources
- Sample Beneficiaries
- STU3 vs FHIR R4 Comparison Tables
- Additional Information
Sections added (and the links to these sections are added from the left-hand navigation):
- Understanding the Data section added, after Authorization and before Calling the API
- Optimizing your application section added after Consuming the data
Support page: 
Period added to the end of this sentence: "To get help with questions …

Documentation updates

---

_codebooks/codebook-mbsf-abcd.xml
_plugins/api_codings.rb

[BFD-2803](https://jira.cms.gov/browse/BFD-2803)
1. This ticket aims to address and resolve checkstyle related issues with the documentation of the blue button website. Specifically, the ticket focuses on fixing errors related to the usage of the question marks within the documentation. The presence of the improperly formatted questions marks have led to an improper render on the website.
`Example:` 
https://bluebutton.cms.gov/resources/variables/ptdcntrct01/
https://bluebutton.cms.gov/resources/variables/buyin01/
1. Fixes Checkstyle Error. 
* Documentation.
* Reference the Unicode of the character  ex: https://www.compart.com/en/unicode/U+FFFD
Submitters should complete …

BFD-2803: Fixed Checkstyle errors related to Question Mark

---

_includes/footer.html

[BB2-2473](https://jira.cms.gov/browse/BB2-2473)
plan writing link was missing and been fixed to route to a correct page.
Reviewers should click the footer link of "Plain Writing" and go the correct page.
* TODO
It doesn't have security implication.
* Does this PR modify or invalidate any of our security controls?  **No**.
* Does this PR store or transmit data that was …

bb2-2473 fixed link for the plain writing

---

_pages/developers.md

[BB2-2568](https://jira.cms.gov/browse/BB2-2568)
* TODO
Check the changes in the updated sample bene ids
* Does this PR modify or invalidate any of our security controls?  **No**.
* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and …

BB2-2568 updated sample ids

---

ops/Jenkinsfile.cbc-build-deploy-akamai

[BB2-2517](https://jira.cms.gov/browse/BB2-2517)
Removed the options for prod.
* TODO
* Does this PR modify or invalidate any of our security controls?**No**.
* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR …

bb2-2517-removed prod option

---

_layouts/basic.html
_layouts/default-full.html
_layouts/default.html
_layouts/layout-for-data-tables.html

[BB2-2623](https://jira.cms.gov/browse/BB2-2623)
Medium vulnerability.
Invicti Enterprise identified the target web site is using jQuery and detected that it is out of date. 
Please upgrade your installation of jQuery to the latest stable version.
jQuery integration copied from here: https://releases.jquery.com/
Upgrades jQuery from version 3.2.1 to 3.7.1
* Review any front end items that leverage jQuery and confirm there are no issues
* Check the source and confirm the jquery update: view-source:https://test.static.bluebutton.cms.gov/
* If the answer to any of the questions below is **Yes**, then here's a link to …

[ BB2-2623 ] update jquery version from 3.2.1 to 3.7.1

---

_pages/developers.md

[BB2-2565](https://jira.cms.gov/browse/BB2-2565)
Revise new documentation about access grant expiration to include newly decided solution for research apps. Original version of this documentation is here:  https://confluence.cms.gov/x/ew5iN
Add new access grant expiration docs to static website
- Add new subsection, **Access to Medicare enrollee data**, to **Overview** section of developer docs.
- Add content to **Authorization** section of developer docs covering the application categories that receive and can use refresh tokens.
* Typos
* Formatting
* Accuracy of docs
* If the answer to any of the questions below …

bb2-2565-update-access-grant-docs

---

_includes/value-for-benes.html

Fix typo on homepage
[BB2-2836](https://jira.cms.gov/browse/BB2-2836)
The "Value for people with Medicare" section of the BB 2.0 homepage includes the following sentence:
"It also gives beneficiaries and their caregivers more options and control over your claims data."
Changing "your" to "their" makes more sense in this sentence:
"It also gives beneficiaries and their caregivers more options and control over their claims data."
* Fix typo in "Value for people with Medicare" section of homepage
* Typos
* If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact …

BB2-2836 Fix typo on homepage

---

_pages/developers.md

[BB2-2827](https://jira.cms.gov/browse/BB2-2827)
QA new documentation for access grant updates.
Makes changes to developer docs requested by Rachel on QA ticket.
* Typos
* If the answer to any of the …

QA Access Grant Docs

---

_includes/footer.html
_includes/header.html

[BB2-2796](https://jira.cms.gov/browse/BB2-2796)
Changes "API Docs" to "API Reference" in the main site menu to disambiguate it from the "Documentation" link.
- Change "API Docs" to "API Reference" in main site menu.
* Site menu works properly after new text is added.
* Does …

Change "API Docs" to "API Reference" in main menu

---

_includes/bluebutton-ig/navbar.html
_includes/footer.html
_includes/head.html
_includes/value-for-orgs.html
_pages/developers.md
_pages/resources.md
_pages/terms/2022-11-01-terms-of-service.md
_pages/v2.md

[BB2-2669](https://jira.cms.gov/browse/BB2-2669)
There are links on our static site that are absolute that should be relative. When developing locally, these links will go to our production site web server. We are wanting these to be relative, so that any changes can be observed locally for development and in test/staging for QA.
Change all absolute links to the Blue Button static site in the `/pages` and `/_includes` directories to relative links.
* Broken links
* Remaining instances of absolute links in site content
* If the answer to any of the questions below is **Yes**, then here's a link to the associated …

BB2-2669 change absolute to relative links

---

_includes/footer.html

[BB2-2390](https://jira.cms.gov/browse/BB2-2930)
We recently added the production access guide to the main site menu, but neglected to add it to the menu with the same items in the site footer.
- Add link to Production Access Guide to site footer menu.
* Link appears and works correctly in site footer.
* Does this PR modify or invalidate any of our security controls? …

BB2 2930 Add production access guide to footer

---

_pages/developers.md

[BB2-3028](https://jira.cms.gov/browse/BB2-3028)
On the developer docs page of the static website, "Calling the API" and "Consuming the data" are in the wrong order in the left sidebar menu and should be reversed.
AC:
"Consuming the data" comes before "Calling the API" in the left sidebar menu of the Blue Button developer docs page.
- Put "Consuming the data" before "Calling the API" in the sidebar menu for the static side developer docs
- All of the menu items should be in the same order as the document sections
* Order of menu items
* If the answer to any of the questions below is **Yes**, then here's a link to the …

BB2-3028: Fix order of menu items on developer docs

---

_pages/production-access-user-guide.md

[BB2-3030](https://jira.cms.gov/browse/BB2-3030)
The rewritten Production Access Guide has been merged with the main branch of the static website repo and needs to be QA'd as it will appear on the website.
- Add changes to the Production Access Guide text requested by Rachel on QA ticket
* Typos, incorrect formatting, etc.
* Does this PR modify or invalidate any of our …

BB2 3030 QA Production Access Guide

---

_pages/developers.md

[BB2-3055](https://jira.cms.gov/browse/BB2-3055)
The static site developer docs include a reference to the old production access checklist that should be changed to refer to the production access guide instead:
"In order to gain production access, an organization should start by reviewing the Terms of Service and production access user guide. Once an organization believes it is fulfilling all the requirements detailed in the checklist and is adherent to the terms of service, they should email [BlueButtonAPI@cms.hhs.gov](mailto:BlueButtonAPI@cms.hhs.gov) to set up a production access demonstration meeting with the CMS team."
AC:
Change "checklist" to "guide" in the text shown above.
- Change word "checklist" to "guide" in one place in the …

Change "checklist" to "guide"

---

_pages/developers.md

Add Spanish translation instructions to developer docs.
[BB2-3070](https://jira.cms.gov/browse/BB2-3070)
The content from [BB2-2833](https://jira.cms.gov/browse/BB2-2833), in [this Google doc](https://docs.google.com/document/d/1_Ybd55Uzrq7hc6OaRJ15-1dy8MdvdVX5DfIsapadI-E/edit) needs to get added to the developer docs on the static website.
AC:
- Spanish translation developer documentation content is converted to markdown, added to a static website PR, approved by 2 team engineers, and merged with the main branch.
- Add documentation showing how to select the language for the BB2.0 authorization screens
* Correctness and clarity of instructions
* Typos and formatting …

bb2-3070-add-Spanish-translation-content

---

_data/rda_api_data_dictionary.csv

[BFD-3373](https://jira.cms.gov/browse/BFD-3373)
Update BlueButton Static Site with new RDA fields.
Replaces the file _data/rda_api_data_dictionary.csv in BB static site repo with the exported CSV file of tab B) Data Dictionary from the RDA API Data dictionary 
Test the static site locally to verify new variables can be loaded in browser:
- NDC
- NDC-QTY
- NDC-QTY-QUAL
- DTL-NDC
- NDC-UNIT-COUNT
* Does this PR add any new …

BFD-3373: Updates BlueButton Static Site with new RDA fields

---

_pages/developers.md

[BB2-3223](https://jira.cms.gov/browse/BB2-3223)
Two small updates to our documentation on the static site are needed per review of our announcement and documentation for access grant expiration
Made following changes to developers.md file:
1) Changed '(IRB)-regulated' to '(IRB)-approved' 
2) Changed "If an enrollee uses the app more than once, they must reauthorize for each data pull."
to: 
"If an enrollee uses the app more than once outside the 10-hour window, they must reauthorize for each data pull."
Please make sure the updated text is correct as per the ac provided in parent ticket.
* TODO
* If the answer to …

 Updated static text for access grant documentation BB2-3233

---

_pages/developers.md

[BB2-3179](https://jira.cms.gov/browse/BB2-3179)
Update developer documentation for expired data grant for application. This PR lists error which we get while refreshing token with expired data grant
* TODO
* Does this PR store or transmit data that was not stored or …

BB2-3179: Update developer documentation for expired data grant

---

_includes/value-for-orgs.html

[BB2-2834](https://jira.cms.gov/browse/BB2-2834)
Currently, the "Value for Organizations" section of the BB2.0 [homepage](https://bluebutton.cms.gov/) ends with the following text: "View a full list of connected applications to get started, or go ahead and create your Sandbox account to explore our sample data."
However, there is no actual option to view a list of connected apps. "Join the Blue Button Sandbox" sends the user to the Sandbox signup, and "View the use cases" loads the BB2.0 API docs.
This has been reviewed and approved by product.
Adjusts the CTA to make sign up the subordinate link and make the language more consistent. Replaces the missing/broken link.
* …

Updated CTAs in Value for Orgs

---

_pages/resources-variables-fi_orig_clm_cntl_num.md

[BFD-3277](https://jira.cms.gov/browse/BFD-3277)
FI_ORIG_CLM_CNTL_NUM is not mapped correctly in the BB2 static site. 
- Modifies permalink to correct variable name fi_orig_clm_cntl_num instead of fi_orig_cntl_num
* Test that http://localhost:4000/resources/variables/fi_orig_clm_cntl_num/ resolves
* Does this PR modify or invalidate any of our security controls? …

BFD-3277: Modifies permalink to correct variable name

---

.github/pull_request_template.md

[BB2-3252](https://jira.cms.gov/browse/BB2-3252)
Per new PR review security review norm, change the security reviewer as a general instruction.
Update PR review template as per new PR review norm.
* TODO
* Does this PR store or transmit data that was not stored or …

BB2-3252 Update PR template per new PR review norm.

---

_pages/developers.md

[BB2-3244](https://jira.cms.gov/browse/BB2-3244)
Updated docs for expired data access grant
* TODO
* Does this PR store or transmit data that was not stored or transmitted before? **Yes** or **No**.
* If the answer to any of the questions below is **Yes**, then please add a …

BB2-3244: Updated docs for expired data access grant

---

ops/Dockerfile.cbc-build
ops/Jenkinsfile.cbc-build-deploy-akamai
ops/Jenkinsfile.cbc-build-deploy-prod-akamai

[BB2-3275](https://jira.cms.gov/browse/BB2-3275)
Description:
Currently, SCP is used to copy (deploy) site static content built onto the target - Akamai netstorage upload location.
This approach has a drawback that if a resource is removed from the content, SCP does not remove it, the solution is to use rsync to sync the content built and the target netstorage upload location, such that the removed resource will be pruned by the deployment, which is the expected behavior.
Replace SCP with RSYNC in jenkins deployment pipeline.
* TODO
* If the answer to any of the questions below is **Yes**, then here's a link to the …

install rsync and tested out in jenkins

---

_pages/developers.md

[BB2-3298](https://jira.cms.gov/browse/BB2-3298)
Added access_grant_expiration to token response in documentation
* TODO
* Does this PR store or transmit data that was not stored or transmitted before? **Yes** or **No**.
* If the answer to any of the questions below is …

BB2-3298: Added access_grant_expiration to token response

---

ops/Jenkinsfile.cbc-build-deploy-prod-akamai

[BB2-3338](https://jira.cms.gov/browse/BB2-3338)
Removes a duplicate stage name causing issues in static site deployment
None
We will test this via Jenkins after merge and revert if it doesn't work.

Remove duplicate stage

---

ops/Jenkinsfile.cbc-build-deploy-prod-akamai

[BB2-3338](https://jira.cms.gov/browse/BB2-3338)
Adds quotes to rsync steps to ensure the proper path is used.
None
I was able to test this by replaying a Jenkins job with manual script changes incorporated and it seems to have worked: https://ci.backends.cms.gov/non-oc/job/Blue%20Button/job/DEPLOY%20-%20PROD%20Static%20Site%20(Akamai)/40/console
We can try again on master after this is merged.

Fix static site deployment for prod

---

ops/Jenkinsfile.cbc-build-deploy-prod-akamai

[BB2-3338](https://jira.cms.gov/browse/BB2-3338)
Fixes quotes on css rsync step.
None
I was able to test this by replaying a Jenkins job with manual script changes incorporated and it seems to have worked: https://ci.backends.cms.gov/non-oc/job/Blue%20Button/job/DEPLOY%20-%20PROD%20Static%20Site%20(Akamai)/40/console
We can try again on master after this is merged.

Fix static site deployment for prod (follow-up)

---

ops/build_autoincrement_release.sh

[BB2-3357](https://jira.cms.gov/browse/BB2-3357)
- fixes some of the error catching in the auto increment release script
- eliminates tmp file name collisions and adds tmp cleanup to more cases
- adds more verbose output to make it easier to see what the script is doing, and to see where it may be failing
- deletes any created tags if the tags are created but the release creation fails.
- Any unaddressed concerns or pain points?
I've run this to confirm that it behaves the same as the script I made in https://github.com/CMSgov/bluebutton-web-server/pull/1242, and it worked as expected. To test, you may need to comment out the check for the current branch being "master"
Please indicate if this PR …

BB2-3357: Updates to autoincrement script

---

selenium_tests/src/test_site_static.py

[BB2-3311](https://jira.cms.gov/browse/BB2-3311)
Remove Selenium Chrome webdriver opt setting: window-size
this results in the selenium tests VNC web UI rendering takes the default viewport setting which is preferred - page content centered and proportioned in the VNC view, better for tests user interaction checking and trouble shooting.
Remove the line in selenium test case init where the webdriver option : window size is set to a custom size.
Check out the PR to local and run a selenium tests remote or local
Start VNC viewer and observe the web UI interaction in VNC viewer
Expected: the web UI should be centered
Refer to this BB2 web server PR for VNC setup details: …

jimfuqian/BB2-3311 Remove selenium tests webdriver opt setting window-size

---

_config-prod.yml

[BB2-3481](https://jira.cms.gov/browse/BB2-3481)
Changes tealium url in config file to reference the new prod url ("https://tealium-tags.cms.gov/cms-bluebutton/prod/utag.sync.js")
Any previous references to the old url "https://tags.tiqcdn.com/utag/cmsgov/cms-bluebutton/prod/utag.sync.js"
Ran locally and tested major links

re-adding prod tealium url

---

_pages/developers.md

[BB2-3506](https://jira.cms.gov/browse/BB2-3506)
Added docs regarding revoke token endpoint
See attached image

BB2-3506: Added docs regarding revoke token endpoint

---

_config-prod.yml
_config.yml
_includes/footer.html
_includes/head.html

[BB2-BB2-3390](https://jira.cms.gov/browse/BB2-3390)
Implements the tealium gdpr privacy modal as on AB2D.
Currently, tealium tags need to be updated before merging this PR. This complicates local testing as well, though it is possible for the time being to swap out the tags locally to ones with the correct version.
Currently, this can be validated by swapping the tealium tags specified in the code (which point to version controlled tags in Akamai) with versions implemented by AB2D: https://tealium-tags.cms.gov/cms-innovations/prod/utag.sync.js and https://tealium-tags.cms.gov/cms-ab2d/prod/utag.js. Testing may wait until additional tealium updates to simplify this effort or we can jumpstart testing …

BB2-3390: Implement privacy modal

---

_pages/developers.md

[BB2-3529](https://jira.cms.gov/browse/BB2-3529)
This PR makes some adjustments to the developer documentation to include PKCE parameters in our auth request examples.
Do these steps actually work? Do the descriptions make sense from a technical perspective?
Go to https://test.static.bluebutton.cms.gov/developers/ to view these changes in the test environment.

BB2-3529: Doc updates for PKCE

---

_pages/developers.md

[BB2-3529](https://jira.cms.gov/browse/BB2-3529)
This PR makes some adjustments to the developer documentation to include PKCE parameters in our auth request examples.
Do these steps actually work? Do the descriptions make sense from a technical perspective?
Go to https://test.static.bluebutton.cms.gov/developers/ to view these changes in the test environment.

BB2-3529: Doc updates for PKCE (Part 2)

---

_pages/developers.md

[BB2-3739](https://jira.cms.gov/browse/BB2-3739)
Added Text for dev to handle 403
"NOTE: When a beneficiary is authorizing your application, they will have the ability to omit the patient/Patient.read scope. Be sure that you build your application accordingly to handle a 403 error if a beneficiary decides to filter their demographic information.
Run bb2 static site locally and view if text is visible

BB2-3739: Add note for handling 403 if patient/Patient.read scope is missing

---

_pages/developers.md

[BB2-3738](https://jira.cms.gov/browse/BB2-3738)
Updated the developer documentation to show the `openid` scope, and to demonstrate how scopes can be requested on auth requests. Additionally, a small correction to have realistic PKCE values in our example.
- Are the updates clear? Do the examples work?
- Should we use realistic PKCE values in examples, or does that enable users to not generate their own code verifiers?
Check the deployed Test static site [here](https://test.static.bluebutton.cms.gov/developers/) and compare to the prod version of the site [here](https://bluebutton.cms.gov/developers/).
* …

Updates to scopes and openid documentation.

---

_pages/developers.md

[BB2-3600](https://jira.cms.gov/browse/BB2-3600)
Updates some of the language for the state parameter to make it mandatory.
Any other portions of the code that have incorrect references.

updating state params to be required

---

_config.yml
_pages/resources.md
docker-compose.selenium.yml
docker-compose.yml

[BB2-3856](https://jira.cms.gov/browse/BB2-3856)
Disable "Blue Button Implementation Guide (Blue Button V1)" from BB2 site "Resources" page and also EXCLUDE the assets for the BB2 IG (V1) so that it won't participate in the web page generation.
1. Removed the link to BB2 V1 IG web resources (assets/ig) from the "Resources" landing page
2. Exclude assets/ig folder in _config.yml
1.  Verify on TEST site that the BB2 V1 IG link is no longer on "Resources" landing page
2. Verify that BB2 V1 IG web page is not accessible direct from <domain>/assets/ig (404)
* Adds new transmission …

jimfuqian/BB2-3856 Disable v1 Blue Button IG (Obsolete) but keep the meta assets for archive

---

_pages/production-access-user-guide.md

[BB2-3832](https://jira.cms.gov/browse/BB2-3832)
Updates missed reference to the old number of synthetic users.
Any other spots that we need to check?
Go to the production access guide page in the static site to confirm how it looks.

Update missed reference to 40000 users.

---

ops/cbc-build-push.sh
ops/cbc-build.yaml

[BB2-4010](https://jira.cms.gov/browse/BB2-4010)
Updating GFM changes in Public ECR Image from Greenfield Account

Deploy Static Site via Jenkins Using Public ECR Image from Greenfield Account

---

CODE_OF_CONDUCT.md
COMMUNITY.md
CONTRIBUTING.md
GOVERNANCE.md
LICENSE
README.md
SECURITY.md
code.json

[BB2-4031](https://jira.cms.gov/browse/BB2-4031)
Updates the repository to fall in line with Tier 3 Repo Maturity Model
Spelling

BB2-4031: Update Repo to Tier 3
